### PR TITLE
fix: remove unnecessary components

### LINKED ISSUE #375: Remove unnecessary examples of components
### Subject

Remove unnecessary examples of components

### Description

The following component examples are similar to what is written in the Yamada UI documentation and should be removed to make them more unique to Yamada Components.

- [button-group](https://github.com/yamada-ui/yamada-components/tree/main/contents/forms/button-group)
- [buttons](https://github.com/yamada-ui/yamada-components/tree/main/contents/forms/buttons)
- [checkboxes](https://github.com/yamada-ui/yamada-components/tree/main/contents/forms/checkboxes)
- [inputs](https://github.com/yamada-ui/yamada-components/tree/main/contents/forms/inputs)
- [circular-avatar](https://github.com/yamada-ui/yamada-components/tree/main/contents/data-display/avatars/circular-avatar)
- [centered-full-width](https://github.com/yamada-ui/yamada-components/tree/main/contents/navigation/paginations/centered-full-width)
- [with-full-width](https://github.com/yamada-ui/yamada-components/tree/main/contents/disclosure/tabs/with-full-width)
- [with-close-button-on-outside](https://github.com/yamada-ui/yamada-components/tree/main/contents/overlay/drawers/with-close-button-on-outside)
- [simple-menu](https://github.com/yamada-ui/yamada-components/tree/main/contents/overlay/menus/simple-menu)

### Are you willing to participate in the development of this feature and create a pull request?

None

### PR DESCRIPTION
**Pull request by illionillion**
Closes #375

### CODE REVIEW

**Comment by Haru-0001** [comment]
Isn't [WithCloseButtonOnOutside](contents/overlay/drawers/with-close-button-on-outside) similar to what is described in the document?

**Review by taroj1205 — COMMENTED** [review]
Thanks for your PR!

Please also delete the following:
- [with-close-button-on-outside](https://github.com/yamada-ui/yamada-components/tree/main/contents/overlay/drawers/with-close-button-on-outside?rgh-link-date=2024-07-24T04%3A19%3A27Z)

**Comment by illionillion** [comment]
@Haru-0001 @taroj1205 
Removed `with-close-button-on-outside` please review once.

**Review by taroj1205 — APPROVED** [review]
LGTM thanks!

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
