### PR TITLE
Added `Dialogs` example

### PR DESCRIPTION
**Pull request by Haru-0001**
Related #152

## Description

Added example of cookie dialog.

## Is this a breaking change (Yes/No):

No.

## Additional Information

I will add examples other than cookies as soon as I create them.

### CODE REVIEW

**Review by taroj1205 — CHANGES_REQUESTED** [review]
Thanks for the PR! I have made a few suggestions, please check!

**Comment by Haru-0001** [comment]
@taroj1205 
I have made the correction. I would appreciate it if you could re-review it.

**Review by taroj1205 — APPROVED** [review]
LGTM Thanks!

**Comment by Haru-0001** [comment]
@taroj1205 
I apologize for the inconvenience. As I refactored earlier, could you please review it again?

**Review by taroj1205 — APPROVED** [review]

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
