### PR TITLE
feat(input): added `input` with overlay

### LINKED ISSUE #482: Add password confirmation with overlay example
### Subject

Input

### Description

https://x.com/wickedmishra/status/1831361580396884190?s=46

### Are you willing to participate in the development of this component and create a pull request?

Yes

### PR DESCRIPTION
**Pull request by taroj1205**
Closes #482

## Description

I have added a password confirmation input example with an overlay.

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by Shunii85 — COMMENTED** [review]
I entered the maximum length string in the input and the indicator overflowed the input.
And, I think that it is seems not to appropriate the width.

**Comment by Shunii85** [comment]
> I entered the maximum length string in the input and the indicator overflowed the input.

**Comment by Shunii85** [comment]
> I entered the maximum length string in the input and the indicator overflowed the input.
It was hard for me to see where the password ended up.

**Comment by taroj1205** [comment]
@Shunii85 I have implemented a fix, please check.

**Review by Shunii85 — COMMENTED** [review]
@taroj1205 I'm sorry I am late!! Thanks for the changes.
I can see not to over placeholder with indicator! But, I cannot see the improvement with the indicator width.
Is it impossible? I don't know if I can approve. So,

**Comment by taroj1205** [comment]
> @taroj1205 I'm sorry I am late!! Thanks for the changes. I can see not to over placeholder with indicator! But, I cannot see the improvement with the indicator width. Is it impossible? I don't know if I can approve. So,

Could you please show me a screenshot of how it looks on your screen? It seemed fine on my screen.

**Comment by Shunii85** [comment]
@taroj1205 
Please check this!
Screenshot from 2024-09-15 20-27-24

**Comment by Haru-0001** [comment]
@illionillion @Shunii85 
The overflow of the indictor as indicated has been corrected. Please check again.

**Review by illionillion — APPROVED** [review]

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
