### PR TITLE
Fix pagination alignment

### PR DESCRIPTION
**Pull request by Ncode-93**
## Description
This PR addresses the issue of pagination layout misalignment between 1-digit, 2-digit, and 3-digit page numbers, which was causing inconsistent spacing in the pagination component. The changes ensure that page numbers remain consistently aligned regardless of the number of digits displayed (e.g., page 1, page 10, page 100).

## Current behavior (updates)
-> Adjusted the pagination component's styling to ensure that page numbers of varying digit lengths (1-digit, 2-digit, 3-digit) are consistently aligned.
-> Introduced flexible padding and margin adjustments to handle cases where digit lengths change as the user navigates through different pages.
-> Reviewed and tested on various screen sizes to ensure the layout remains responsive.

## New behavior
_Before_: Inconsistent alignment for 1-digit and 2-digit pages.
_After_: Properly aligned pagination numbers across all digit lengths.

## Testing:
Manually tested on various browsers and devices.
Confirmed that the issue no longer appears when navigating through pages with different digit counts (e.g., 1, 10, 100).

## Additional Information
The package.json and package-lock.json files were modified due to running npm install during local development, but no dependencies were changed manually. If these changes are unnecessary, they can be reverted.

## Is this a breaking change (Yes/No): No, it's not.

### CODE REVIEW

**Comment by illionillion** [comment]
@Ncode-93 

Thanks for the PR.
The number of file diffs is very large, did you check out from the latest main branch?
And PR should be created for the main branch.

**Comment by illionillion** [comment]
Use pnpm, not npm.
Do not include differences in dependencies such as package.json.

**Comment by Ncode-93** [comment]
@illionillion 
I'll be closing this one and issuing a new one with all the corrections mentioned.

**Comment by illionillion** [comment]
> @illionillion I'll be closing this one and issuing a new one with all the corrections mentioned.

@Ncode-93 
I apologize for the inconvenience and thank you in advance for your cooperation.

**Pull request closed without merging**
