### PR TITLE
fix: remove unnecessary options

### PR DESCRIPTION
**Pull request by illionillion**
Closes #

### CODE REVIEW

**Comment by hirotomoyamada** [comment]
@illionillion 

Why erase the initial value when most components require margins?

**Comment by illionillion** [comment]
> @illionillion 
> 
> Why erase the initial value when most components require margins?

I deleted them as they both appear to have the same content.

**Comment by illionillion** [comment]
> > @illionillion
> > Why erase the initial value when most components require margins?
> 
> I deleted them as they both appear to have the same content.
> 
> 



> > @illionillion
> > Why erase the initial value when most components require margins?
> 
> I deleted them as they both appear to have the same content.
> 
> 



> > @illionillion
> > Why erase the initial value when most components require margins?
> 
> I deleted them as they both appear to have the same content.
> 
> 

It is no problem.

**Comment by hirotomoyamada** [comment]
@illionillion 

I was wrong. Sorry.

**Review by Tomoya-Matsubara — APPROVED** [review]

**Review by Hayato1031 — APPROVED** [review]

**Pull request merged**
