### PR TITLE
Fixed component styles

### PR DESCRIPTION
**Pull request by hirotomoyamada**
## Description

Fixed component styles.

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by illionillion — APPROVED** [review]

**Comment by taroj1205** [comment]
So it looks like this PR will add `containerType` as default, did you mean to remove all `containerType` from `metadata.json` or will this be a separate PR?

**Comment by hirotomoyamada** [comment]
@taroj1205 

I decided to have containerType internally regardless of the options in metadata.json.

https://github.com/yamada-ui/yamada-components/pull/204/files#diff-c3bb76cb918a56f5f03d62b2de596eec3075be45460ec690db4f7da328c57d91

**Review by taroj1205 — COMMENTED** [review]
Please remove `containerType` from the following files:
- https://github.com/yamada-ui/yamada-components/blob/fix/components/styles/contents/layouts/footers/footer-centerd/index.tsx
- https://github.com/yamada-ui/yamada-components/blob/fix/components/styles/contents/layouts/footers/footer-links/index.tsx
- https://github.com/yamada-ui/yamada-components/blob/fix/components/styles/contents/layouts/footers/footer-simple/index.tsx
- https://github.com/yamada-ui/yamada-components/blob/fix/components/styles/contents/layouts/footers/footer-social-icons/index.tsx
- https://github.com/yamada-ui/yamada-components/blob/fix/components/styles/contents/layouts/headers/double-header/index.tsx
- https://github.com/yamada-ui/yamada-components/blob/fix/components/styles/contents/layouts/headers/simple-header/index.tsx

**Comment by hirotomoyamada** [comment]
@taroj1205 

Fixed `containerType`.

**Review by taroj1205 — APPROVED** [review]
LGTM

**Review by illionillion — APPROVED** [review]

**Pull request merged**
