### PR TITLE
chore: remove background color prop from header Flex component

### LINKED ISSUE #489: FIx `headers/with-tabs` Components backGroundColor
### Subject

FIx `headers/with-tabs` Components backGroundColor

### Description

Fix to Header background light black, body and tab background dark black.

image

### Are you willing to participate in the development of this component and create a pull request?

None

### PR DESCRIPTION
**Pull request by 0xtkey256**
Closes #489 

## Description

"Remove 'blackAlpha' background in header Flex component for black/white mode"
## Current behavior (updates)

The background color is slightly gray.

## New behavior

The background color goes back to normal.

## Is this a breaking change (Yes/No):
No

## Additional Information
Nada

### CODE REVIEW

**Review by illionillion — CHANGES_REQUESTED** [review]
This makes it hard to tell which is the tab and which is the header.

image

Please clarify the difference between headers and tabs like Mantine.

image

> Fix to Header background light black, body and tab background dark black.

**Comment by 0xtkey256** [comment]
@illionillion 
Could you check the update commit again? Is it too distinctive? 
### Light Mode:
White background withTabs

### Dark Mode:
Black background withTabs

**Comment by illionillion** [comment]
@0xtkey256 

The tabs that are not active should be the same color as the header background.

**Comment by 0xtkey256** [comment]
@illionillion 
 I've set the same color as the header background.

**Review by illionillion — COMMENTED** [review]
@0xtkey256 
When in light mode, the original code looks better, so please put it back.

image

**Review by illionillion — APPROVED** [review]

**Pull request merged**
