### PR TITLE
Add DateRangeTemperatureChart

### PR DESCRIPTION
**Pull request by illionillion**
Related #442  

## Description

Fixed because it disappeared in another PR.

### CODE REVIEW

**Review by 108yen — COMMENTED** [review]
Removed due to refactoring to `TemperatureChart`.

**Comment by illionillion** [comment]
> Removed due to refactoring to `TemperatureChart`.

Wouldn't it be more appropriate to say that it was not a refactoring, but a reworking into something completely different?

**Comment by illionillion** [comment]
> > Removed due to refactoring to `TemperatureChart`.
> 
> Wouldn't it be more appropriate to say that it was not a refactoring, but a reworking into something completely different?

I created a new component called DateRangeTemperatureChart.

**Comment by 108yen** [comment]
@illionillion 
The original TemperatureChart was not cool, so we fixed it.
I don't think it is necessary since the functions are overlapping, what do you think?

**Comment by illionillion** [comment]
> @illionillion The original TemperatureChart was not cool, so we fixed it. I don't think it is necessary since the functions are overlapping, what do you think?

Wouldn't it be better to be able to display more than one graph for a single region?
It would be more functional if the time period could also be specified in `range`.
The functionality is the same, but the ideology is different, so leave it.

**Comment by illionillion** [comment]
#446 We were working on the same content, so I'll close it.

**Comment by 108yen** [comment]
@illionillion 

> Wouldn't it be better to be able to display more than one graph for a single region?

If it can be done in a cool way, I agree.

> It would be more functional if the time period could also be specified in range.

I do not agree with this.
This is not a chart example, but an example of data fetching by RangeDatePicker.

**Comment by illionillion** [comment]
> I do not agree with this. This is not a chart example, but an example of data fetching by RangeDatePicker.
@108yen 
Then why not just give it as an example of Range and there would be no problem?

**Comment by 108yen** [comment]
@illionillion 
The premise is that Yamada Component is a collection of component examples, so there is no need for complex data acquisition examples.
Please correct me if my premise is incorrect.

**Pull request closed without merging**
